name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        path: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
      
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pandas sqlalchemy numpy


    - name: Execute Tests
      run: |
        chmod u+r+x ./main/project/tests.sh
        cd ./main/project
        ./tests.sh
